CREATE DATABASE `almacen` /*!40100 DEFAULT CHARACTER SET latin1 */$$

delimiter $$

CREATE TABLE `users` (
  `USER_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(45) DEFAULT NULL,
  `PASSWORD` varchar(100) DEFAULT NULL,
  `ENABLED` tinyint(1) NOT NULL DEFAULT '0',
  `NON_LOCKED` tinyint(1) NOT NULL DEFAULT '0',
  `NON_EXPIRED` tinyint(1) NOT NULL DEFAULT '0',
  `NON_CREDENTIAL_EXPIRED` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8$$

delimiter $$

CREATE TABLE `user_roles` (
  `USER_ROLE_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `USER_ID` int(10) DEFAULT NULL,
  `AUTHORITY` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`USER_ROLE_ID`),
  UNIQUE KEY `USER_ROLE_ID_UNIQUE` (`USER_ROLE_ID`),
  KEY `FK_user_roles` (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8$$

delimiter $$

CREATE TABLE `disco` (
  `IDENT` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(45) DEFAULT NULL,
  `GRUPO` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`IDENT`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1$$

delimiter $$

CREATE TABLE `cancion` (
  `IDENT` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(45) DEFAULT NULL,
  `DURACION` varchar(8) DEFAULT NULL,
  `IDDISCO` int(11) DEFAULT NULL,
  `POSICION` int(11) DEFAULT NULL,
  PRIMARY KEY (`IDENT`),
  KEY `FK_INT_DIS_idx` (`IDDISCO`),
  CONSTRAINT `FK_CAN_DIS` FOREIGN KEY (`IDDISCO`) REFERENCES `disco` (`IDENT`),
  CONSTRAINT `FK_INT_DIS` FOREIGN KEY (`IDDISCO`) REFERENCES `disco` (`IDENT`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1$$

delimiter $$

CREATE TABLE `interprete` (
  `IDENT` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(45) DEFAULT NULL,
  `INSTRUMENTO` varchar(45) DEFAULT NULL,
  `IDDISCO` int(11) DEFAULT NULL,
  PRIMARY KEY (`IDENT`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1$$

delimiter $$

CREATE TABLE `libro` (
  `IDENT` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(45) DEFAULT NULL,
  `AUTOR` varchar(45) DEFAULT NULL,
  `ARGUMENTO` varchar(200) DEFAULT NULL,
  `PAGINAS` int(11) DEFAULT NULL,
  `SERIE` varchar(45) DEFAULT NULL,
  `VOLUMEN` int(11) DEFAULT NULL,
  `PUBLICACION` date DEFAULT NULL,
  PRIMARY KEY (`IDENT`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1$$
