package es.home.almacen.bbdd.bean;

// Generated 01-mar-2013 9:51:56 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Interprete generated by hbm2java
 */
@Entity
@Table(name = "interprete", catalog = "almacen")
public class Interprete implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer ident;
	private String nombre;
	private String instrumento;

	public Interprete() {
	}

	public Interprete(final Integer ident) {
		this.ident = ident;
	}

	public Interprete(final Integer ident, final String nombre, final String instrumento) {
		this.ident = ident;
		this.nombre = nombre;
		this.instrumento = instrumento;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "IDENT", unique = true, nullable = false)
	public Integer getIdent() {
		return ident;
	}

	@Column(name = "INSTRUMENTO", length = 8)
	public String getInstrumento() {
		return instrumento;
	}

	@Column(name = "NOMBRE", length = 45)
	public String getNombre() {
		return nombre;
	}

	public void setIdent(final Integer ident) {
		this.ident = ident;
	}

	public void setInstrumento(final String instrumento) {
		this.instrumento = instrumento;
	}

	public void setNombre(final String nombre) {
		this.nombre = nombre;
	}

}
