delimiter $$

CREATE DATABASE `almacen` /*!40100 DEFAULT CHARACTER SET latin1 */$$

delimiter $$

CREATE TABLE `libro` (
  `IDENT` int(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(45) DEFAULT NULL,
  `AUTOR` varchar(45) DEFAULT NULL,
  `ARGUMENTO` varchar(200) DEFAULT NULL,
  `PAGINAS` int(11) DEFAULT NULL,
  `SERIE` varchar(45) DEFAULT NULL,
  `VOLUMEN` int(11) DEFAULT NULL,
  PRIMARY KEY (`IDENT`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1$$
